[package]

name = "lazysort"
version = "0.0.4"
authors = ["Ben Ashford"]
license = "Apache-2.0"
repository = "https://github.com/benashford/rust-lazysort"
description = "Lazy sorting for iterators"
readme = "README.md"
