[package]

name = "lazysort"
version = "0.0.1"
authors = ["Ben Ashford"]
license = "Apache 2.0"
repository = "https://github.com/benahford/rust-lazysort"
description = "Lazy sorting for iterators"
readme = "README.md"
